<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Activity_Interaction_Coefficient_Calculator_UEM1</RootNamespace>
    <Nullable>enable</Nullable>
    
	<UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>Snipaste_2024-12-05_11-09-16.jpg</PackageIcon>
    <StartupObject>Activity_Interaction_Coefficient_Calculator_UEM1.Program</StartupObject>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <UseWPF>True</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Images\nws.bmp" />
    <None Remove="Images\phi.bmp" />
    <None Remove="Images\v.bmp" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\nws.bmp" />
    <Resource Include="Images\phi.bmp" />
    <Resource Include="Images\v.bmp" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="SQLitePCLRaw.core" />
    <PackageReference Include="System.Data.SQLite" />
    
  </ItemGroup>
  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>