<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MathNet.Numerics" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="9.0.9" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.10" />
    <PackageVersion Include="SQLitePCLRaw.core" Version="2.1.10" />
    <PackageVersion Include="System.Data.SQLite" Version="2.0.2" />
  </ItemGroup>
</Project>